acceleration_limits:
  values:
    joint_1: 3.49065850399
    joint_2: 3.49065850399
    joint_3: 3.49065850399
    joint_4: 17.4532925199
    joint_5: 17.4532925199
    joint_6: 17.4532925199

collision:
  disabled_pairs:
    - {link1: base_link, link2: link_1, reason: Adjacent}
    - {link1: link_1,    link2: link_2, reason: Adjacent}
    - {link1: link_1,    link2: link_3, reason: Unverified}
    - {link1: link_1,    link2: link_4, reason: Unverified}
    - {link1: link_2,    link2: link_3, reason: Adjacent}
    - {link1: link_3,    link2: link_4, reason: Adjacent}
    - {link1: link_4,    link2: link_5, reason: Adjacent}
    - {link1: link_4,    link2: link_6, reason: Unverified}
    - {link1: link_5,    link2: link_6, reason: Adjacent}

# J1, J2, J3 -> 218 deg/sec
# J4, J5, J6 -> 270 deg/sec

# Jerk
# J1, J2, J3 -> 2000 deg/sec^3
# J4, J5, J6 -> 10000 deg/sec^3
# X, Y, Z -> 18000 mm/sec^3
# RX, RY, RZ -> 9000 deg/sec^3
