acceleration_limits:
  source: placeholder
  values:
    joint_1: 3.0
    joint_2: 3.0
    joint_3: 3.0
    joint_4: 3.0
    joint_5: 3.0
    joint_6: 3.0

collision:
  disabled_pairs:
    - {link1: base_link, link2: link_1, reason: Adjacent}
    - {link1: link_1,    link2: link_2, reason: Adjacent}
    - {link1: link_1,    link2: link_3, reason: Unverified}
    - {link1: link_1,    link2: link_4, reason: Unverified}
    - {link1: link_2,    link2: link_3, reason: Adjacent}
    - {link1: link_3,    link2: link_4, reason: Adjacent}
    - {link1: link_4,    link2: link_5, reason: Adjacent}
    - {link1: link_4,    link2: link_6, reason: Unverified}
    - {link1: link_5,    link2: link_6, reason: Adjacent}
